"""Ascension Cost Sheet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vwm6hIqUFOGYc3_JCBjzYuv8dKMajL2q
"""

# -------------------------------------
# Import
import seaborn as sns
import matplotlib.pyplot as plt
import polars as pl

df = pl.read_csv(
    "/Users/qpair/Library/CloudStorage/Box-Box/Q's Cloud/Code Repos/data_science/CostSheet/741109643_dell-seton-medical-center-at-univ-of-texas_standardcharges.csv",
    # encoding="latin-1",
    skip_rows=2,
    ignore_errors=True,
)

dd = (
    df.select(
        [
            "description",
            "standard_charge|discounted_cash",
            "standard_charge|gross",
            "standard_charge|negotiated_dollar",
            "payer_name",
        ]
    )
    .unique(subset=["description"])
    .drop_nulls()
)

dd.sort("standard_charge|negotiated_dollar")
dd.null_count()
dd.head()
